name: Deploy AWS Backend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH and deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: 
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        mkdir -p ~/.ssh
        cp backend/known_hosts ~/.ssh/known_hosts
        ssh -t -i ~/.ssh/id_rsa ubuntu@ec2-13-229-67-43.ap-southeast-1.compute.amazonaws.com "sudo bash ~/deploy.sh"
