name: Deploy AWS Backend

on:
  push:
    branches:
      - testbranch2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH and deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        set -x
        echo "$SSH_PRIVATE_KEY" > keyfile
        chmod 600 keyfile
        ls -ltr keyfile
        cat keyfile
        mkdir -p ~/.ssh
        cp known_hosts ~/.ssh/known_hosts
        cat ~/.ssh/known_hosts
        ssh -t -i keyfile ubuntu@ec2-13-211-144-149.ap-southeast-2.compute.amazonaws.com "sudo bash ~/deploy.sh"
        set +x
